version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - new_pj_network
    volumes:
      - /home/ryuryuryu339/nginx.conf:/etc/nginx/nginx.conf
      - new_pj_static:/data/static/
      - new_pj_media:/data/media/
      - new_pj_log:/var/log/nginx/

  django:
    image: new_pj_django:5
    networks:
      - new_pj_network
    volumes:
      - new_pj_static:/home/new_pj_/staticfiles/
      - new_pj_media:/home/new_pj_/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - new_pj_network
    volumes:
      - new_pj_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  new_pj_network:

volumes:
  new_pj_static:
  new_pj_media:
  new_pj_mariadb:
  new_pj_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true